import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import type { Game, Team, TeamBoxScore, AdvancedStats } from '../types';
import { pct } from './boxScore';

export async function generateAndSharePdf(
  game: Game,
  homeTeam: Team,
  awayTeam: Team,
  homeBoxScore: TeamBoxScore,
  awayBoxScore: TeamBoxScore,
  advancedStats?: AdvancedStats,
): Promise<void> {
  const homeScore = homeBoxScore.totals.points;
  const awayScore = awayBoxScore.totals.points;
  const date = game.gameDate
    ? new Date(game.gameDate).toLocaleDateString('en-AU', { year: 'numeric', month: 'long', day: 'numeric' })
    : '';

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; margin: 0; padding: 20px; color: #0f172a; font-size: 11px; }
    .header { background: #1a2744; color: white; padding: 20px; text-align: center; border-radius: 8px; margin-bottom: 20px; }
    .header h1 { margin: 0; font-size: 22px; letter-spacing: 2px; }
    .score-display { text-align: center; margin: 15px 0; }
    .score-display .score { font-size: 36px; font-weight: bold; }
    .score-display .teams { font-size: 14px; margin-top: 5px; }
    .info { text-align: center; color: #64748b; margin-bottom: 20px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 10px; }
    th { background: #1a2744; color: white; padding: 6px 4px; text-align: center; }
    td { padding: 5px 4px; text-align: center; border-bottom: 1px solid #e2e8f0; }
    tr:nth-child(even) { background: #f8fafc; }
    .totals td { font-weight: bold; background: #e2e8f0; }
    .team-header { background: #1a2744; color: white; padding: 8px 12px; border-radius: 6px; margin: 15px 0 8px; font-weight: bold; }
    .comparison { margin-top: 20px; }
    .comparison td:first-child { text-align: left; font-weight: bold; }
    .footer { text-align: center; color: #64748b; margin-top: 30px; font-size: 10px; border-top: 1px solid #e2e8f0; padding-top: 10px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>GAME REPORT</h1>
  </div>

  <div class="score-display">
    <div class="score">${homeScore} — ${awayScore}</div>
    <div class="teams">${homeTeam.name} vs ${awayTeam.name}</div>
  </div>

  <div class="info">
    ${date ? `<div>${date}</div>` : ''}
    ${game.venue ? `<div>${game.venue}</div>` : ''}
    <div>${game.status === 'completed' ? 'FINAL' : game.status.toUpperCase()}</div>
  </div>

  ${renderBoxScoreTable(homeTeam.name, homeBoxScore)}
  ${renderBoxScoreTable(awayTeam.name, awayBoxScore)}

  ${advancedStats ? renderComparison(homeTeam.name, awayTeam.name, homeBoxScore, awayBoxScore, advancedStats) : ''}

  <div class="footer">
    Generated by Swish Stats — Powered by Swish N' Dish
  </div>
</body>
</html>`;

  const { uri } = await Print.printToFileAsync({ html });
  await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Share Game Report' });
}

function renderBoxScoreTable(teamName: string, bs: TeamBoxScore): string {
  const rows = bs.players
    .map(p => `
      <tr>
        <td style="text-align:left">#${p.playerNumber} ${p.playerName}</td>
        <td>${p.points}</td>
        <td>${p.fgm}-${p.fga}</td>
        <td>${pct(p.fgm, p.fga)}%</td>
        <td>${p.threePm}-${p.threePa}</td>
        <td>${pct(p.threePm, p.threePa)}%</td>
        <td>${p.ftm}-${p.fta}</td>
        <td>${pct(p.ftm, p.fta)}%</td>
        <td>${p.reb}</td>
        <td>${p.ast}</td>
        <td>${p.stl}</td>
        <td>${p.blk}</td>
        <td>${p.to}</td>
        <td>${p.pf}</td>
      </tr>`)
    .join('');

  const t = bs.totals;
  return `
    <div class="team-header">${teamName}</div>
    <table>
      <thead>
        <tr>
          <th style="text-align:left">Player</th>
          <th>PTS</th><th>FG</th><th>FG%</th>
          <th>3PT</th><th>3P%</th>
          <th>FT</th><th>FT%</th>
          <th>REB</th><th>AST</th><th>STL</th><th>BLK</th><th>TO</th><th>PF</th>
        </tr>
      </thead>
      <tbody>
        ${rows}
        <tr class="totals">
          <td style="text-align:left">TOTALS</td>
          <td>${t.points}</td>
          <td>${t.fgm}-${t.fga}</td>
          <td>${pct(t.fgm, t.fga)}%</td>
          <td>${t.threePm}-${t.threePa}</td>
          <td>${pct(t.threePm, t.threePa)}%</td>
          <td>${t.ftm}-${t.fta}</td>
          <td>${pct(t.ftm, t.fta)}%</td>
          <td>${t.reb}</td>
          <td>${t.ast}</td>
          <td>${t.stl}</td>
          <td>${t.blk}</td>
          <td>${t.to}</td>
          <td>${t.pf}</td>
        </tr>
      </tbody>
    </table>`;
}

function renderComparison(
  homeName: string,
  awayName: string,
  homeBS: TeamBoxScore,
  awayBS: TeamBoxScore,
  adv: AdvancedStats,
): string {
  return `
    <div class="team-header">Team Comparison</div>
    <table class="comparison">
      <thead>
        <tr><th style="text-align:left">Stat</th><th>${homeName}</th><th>${awayName}</th></tr>
      </thead>
      <tbody>
        <tr><td>Points</td><td>${homeBS.totals.points}</td><td>${awayBS.totals.points}</td></tr>
        <tr><td>FG%</td><td>${pct(homeBS.totals.fgm, homeBS.totals.fga)}%</td><td>${pct(awayBS.totals.fgm, awayBS.totals.fga)}%</td></tr>
        <tr><td>3PT%</td><td>${pct(homeBS.totals.threePm, homeBS.totals.threePa)}%</td><td>${pct(awayBS.totals.threePm, awayBS.totals.threePa)}%</td></tr>
        <tr><td>FT%</td><td>${pct(homeBS.totals.ftm, homeBS.totals.fta)}%</td><td>${pct(awayBS.totals.ftm, awayBS.totals.fta)}%</td></tr>
        <tr><td>Rebounds</td><td>${homeBS.totals.reb}</td><td>${awayBS.totals.reb}</td></tr>
        <tr><td>Assists</td><td>${homeBS.totals.ast}</td><td>${awayBS.totals.ast}</td></tr>
        <tr><td>Steals</td><td>${homeBS.totals.stl}</td><td>${awayBS.totals.stl}</td></tr>
        <tr><td>Blocks</td><td>${homeBS.totals.blk}</td><td>${awayBS.totals.blk}</td></tr>
        <tr><td>Turnovers</td><td>${homeBS.totals.to}</td><td>${awayBS.totals.to}</td></tr>
        <tr><td>Points in Paint</td><td>${adv.homePointsInPaint}</td><td>${adv.awayPointsInPaint}</td></tr>
        <tr><td>2nd Chance Pts</td><td>${adv.homeSecondChancePoints}</td><td>${adv.awaySecondChancePoints}</td></tr>
        <tr><td>Bench Points</td><td>${adv.homeBenchPoints}</td><td>${adv.awayBenchPoints}</td></tr>
        <tr><td>Biggest Run</td><td>${adv.homeBiggestRun}</td><td>${adv.awayBiggestRun}</td></tr>
        <tr><td>Lead Changes</td><td colspan="2" style="text-align:center">${adv.leadChanges}</td></tr>
        <tr><td>Times Tied</td><td colspan="2" style="text-align:center">${adv.timesTied}</td></tr>
      </tbody>
    </table>`;
}
